### ISSUE TITLE
[DGA] DGA dummy object when using vanilla artisan machines

### ISSUE THREAD

**Issue by Stunky-McDoo** [spacechase0/StardewValleyMods#127]
Im encoutering an issue where any object created by DGA is fed into a vanilla artisan good machine, it creates an output called "DGA dummy object" I have confirmed this happens with the Preserves Jar and Keg, and happens across all the DGA content packs i have tried. No errors are produced in the SMAPI log. (linked https://smapi.io/log/a84298970b524a6794a30923fa8b4ce9)

**Comment by elizabethcd** [comment]
This has been fixed in the latest update (1.4.2).
