### ISSUE TITLE
[Json Assets] ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by Yagisan** [spacechase0/StardewValleyMods#241]
Json Assets 1.10.6 is reporting an ArgumentOutOfRangeException. [SMAPI Log is here.](https://smapi.io/log/8e337778cb024f30bfd5b9772f00cb76)

**Comment by atravita-mods** [comment]
tl;dr I'm a dumbass who can't iterate backwards correctly, fixed in 1.10.7

**Comment by Yagisan** [comment]
Thank you!
