### ISSUE TITLE
[Magic] Photosynthesis only affects main farm

### ISSUE THREAD

**Issue by ghost** [spacechase0/StardewValleyMods#247]
Spell description suggests it affects whichever location you're currently in, however using it on ginger island doesn't affect the crops there, but does affect the crops back on the main farm

**Comment by nico-abram** [comment]
It also doesn't seem to affect farming areas from other mods, like grandpa's shed in SVE or the summit farm from ridgeside village

**Comment by nico-abram** [comment]
At a glance, it looks like adding the ginger island farm should be as simple as adding it to this list: https://github.com/spacechase0/StardewValleyMods/blob/f79a6ccab21cef5bbc6f9d9421244032fa97fd2b/Magic/Framework/Spells/PhotosynthesisSpell.cs#L36-L42

**Comment by nico-abram** [comment]
Sent a pull request with a patch that adds ginger island and ridgeside/SVE farms https://github.com/spacechase0/StardewValleyMods/pull/256

I'll leave the precompiled output from that patch here if anyone wants it:

<details>
<summary>Old</summary>
[Magic 0.8.1.zip](https://github.com/spacechase0/StardewValleyMods/files/9304704/Magic.0.8.1.zip)
</details>

EDIT: Added grampleton fields after someone requested it on the SV discord:
[Magic 0.8.1.zip](https://github.com/spacechase0/StardewValleyMods/files/9310684/Magic.0.8.1.zip)


Use at your own risk, no warranty, etc etc yadda yadda
