### ISSUE TITLE
Luck Skill Level 5 options don't match documentation.

### ISSUE THREAD

**Issue by Yagisan** [spacechase0/StardewValleyMods#31]
My level 5 options are:

Fortunate, or Popular Helper.

![image](https://user-images.githubusercontent.com/172080/128703358-078e72a0-82c6-4f48-9813-3fd40e54fae3.png)

Documentation suggests that it should be Fortunate, or Un-unlucky.

**Comment by Pathoschild** [comment]
Fixed in `develop` and on the mod page. Thanks for reporting it!
