### ISSUE TITLE
spacecore for mobile error

### ISSUE THREAD

**Issue by shinei29** [spacechase0/StardewValleyMods#359]
![Screenshot_20230629-184533](https://github.com/spacechase0/StardewValleyMods/assets/136157750/b95f1493-2d94-4870-89a6-dc32f4012f7a)
Why do I get this, is there a solution?

**Comment by spacechase0** [comment]
@ZaneYork

**Comment by ZaneYork** [comment]
It is not available right now, please wait for mobile 3.18.3.2 release for IL rewrite support

**Comment by KuyaREO** [comment]
> It is not available right now, please wait for mobile 3.18.3.2 release for IL rewrite support

Not rushing you or anything, but is there any expected release for 3.18.3.2? Not going to have Wi-Fi network foe a while so I'm starting to make my modpack right now for that but there's that SpaceCore error..

**Comment by shinei29** [comment]
![Screenshot_20230708-071749](https://github.com/spacechase0/StardewValleyMods/assets/136157750/6c096920-02bf-43dd-a4ba-1c1939a4c457)

still the same error is not compatible with android smapi yet? (i have version 3.18.3.2)
