### ISSUE TITLE
A bug regarding the latest version of Android SMAPI 3.18.3.1, I didn't add any other redundant mods

### ISSUE THREAD

**Issue by 1523006317** [spacechase0/StardewValleyMods#360]
I like this mod very much, I hope the author can update this mod compatible and adapted version for mobile and Android users, thank you very much for the author's hard    @spacechase0 🌷, here is my game log:  https://smapi.io/log/fbd19a95fb8a4ee38cef090689260ec1

**Comment by 1523006317** [comment]
![-49d9e440dd9c1259](https://github.com/spacechase0/StardewValleyMods/assets/132871179/4daa8757-3b14-42d1-b805-adae12ee7082)

**Comment by spacechase0** [comment]
See #359
