### ISSUE TITLE
Space core Mobile version 3.18.3.2 error?

### ISSUE THREAD

**Issue by shinei29** [spacechase0/StardewValleyMods#362]
![Screenshot_20230708-071749](https://github.com/spacechase0/StardewValleyMods/assets/136157750/6c096920-02bf-43dd-a4ba-1c1939a4c457)

still the same error is not compatible with android smapi yet? (i have version 3.18.3.2)

**Comment by 1523006317** [comment]
I'm the same, it really doesn't work on the latest version of android SMAPI and says error This is my game log:  https://smapi.io/log/11d9b9d24e9240d08e14abd894ecfe73     @spacechase0

**Comment by spacechase0** [comment]
@ZaneYork If you don't want to do another pull request that's fine, just not sure if you've seen this.

**Comment by ZaneYork** [comment]
> @ZaneYork If you don't want to do another pull request that's fine, just not sure if you've seen this.

The mobile serilizer does not have `System.Xml.Serialization.StructModel` class, so this patcher cannot works. I'm not sure this patcher's effect if it does not works. simply comment it can ignore this error.

**Comment by spacechase0** [comment]
Hmm, interesting. How does serialization work on mobile? Are all the classes pregenerated?

That patch lets mods attach properties to existing classes. I'm not sure anyone uses it besides some of my mods.

**Comment by Vylesh** [comment]
@spacechase0 Sir Weirdly Bug net Mod Gives Error As well https://smapi.io/log/29fa929bf8634fc19df413aa7e7cb25f

**Comment by KawaiFoxHappyClaws76** [comment]
Example Spacecore makes Museum Buggy Like Museum not Saves Artifacts and Erases Given artifacts later
![Screenshot_20230716-110739.jpg](https://github.com/spacechase0/StardewValleyMods/assets/83465565/49fd9ddd-800b-4131-af5d-ec9a47849602)

![Screenshot_20230716-123647.jpg](https://github.com/spacechase0/StardewValleyMods/assets/83465565/9f9e3efc-71b7-424c-8dd8-0ba3a9354942)

**Comment by Vylesh** [comment]
Example Spacecore makes Museum Buggy Like Museum not Saves Artifacts and Erases Given artifacts later
![Screenshot_20230716-110739.jpg](https://github.com/spacechase0/StardewValleyMods/assets/83465565/49fd9ddd-800b-4131-af5d-ec9a47849602)

![Screenshot_20230716-123647.jpg](https://github.com/spacechase0/StardewValleyMods/assets/83465565/9f9e3efc-71b7-424c-8dd8-0ba3a9354942)

İn short mods Can work buggy but sometimes makes mods unplayable you can install but sometime later game brokes itself
