### ISSUE TITLE
DGA ObjectId from object name Token/Accessor?

### ISSUE THREAD

**Issue by sfortier32** [spacechase0/StardewValleyMods#385]
I've been trying to use some combination of DGA, Content Patcher, and Json Assets that allows an item's occurrence in the player's inventory to alter custom recipes (i.e., reduce ingredient costs). 

This hasn't been possible because I can't access crafting custom recipe ids (if they even exist) through JA, and DGA has id's for these objects, but no current way of accessing them. I've created a new mod to create custom tokens, but I can't figure out how to rewrite DGA's API so that I can **access an IDGAItem's FullID by object name.**

If a token or function could be added, or if there's a workaround already available, please help!

**Comment by sfortier32** [comment]
For additional information: I've tried adding the HasItem token that I want to use (from Expanded Preconditions Utility) into DGA, and (1) SpaceCore struggles to compile because it says i18n isn't available in the Mod.cs context and, (2) even when fixed, there's an "Error applying dynamic field: System.NullReferenceException" at line 86 in DGA/PackData/DynamicFieldData.

**Comment by spacechase0** [comment]
DGA doesn't work very well when needing to be accessed from outside the mod. I'm not really sure I understand what functionality you need.

DGA also isn't surviving into 1.6 - most of its functionality will be in SpaceCore for extending normal custom items (instead of through a content pack).

**Comment by sfortier32** [comment]
I'll probably just skip adding the feature then if I'll have to rewrite a lot after 1.6, but to explain a little more clearly:

I wanted to use the hasItem (aka player has item in inventory) token from EPU and dynamic fields in DGA to edit a crafting recipe when a user has an item in their inventory. I can't use JA since crafting recipes aren't separate from their object, and so there's no recipe id I can reference to conditionally edit with Content Patcher's "EditData" action. (This is what I'm assuming from debug command output). 

With DGA there were a few options, but the main limitation is that my token (hasItem), if not coded into DGA itself, needs to be used in a content pack where it's a dependency. If it's not part of the DGA though, I need DGA to have a token that returns an object's id number given its name. I think this means return full id given string id (not given object item like it is now).

Thanks for responding!

**Comment by spacechase0** [comment]
For JA, the crafting recipe ID is the same as the object's "Name" field.

**Comment by sfortier32** [comment]
Sorry, I meant it's global/full ID like the number. They have the same name, so getting the id by name always returns the object data.

**Comment by spacechase0** [comment]
Crafting recipes don't have a number - they're just a string for the ID. If you run `patch export Data/CraftingRecipes` in the SMAPI console, you should see the JA ones in there too. They just share a name with their object name.

**Comment by sfortier32** [comment]
That's such a good point, but it seems like content patcher is patching before JA is inserting my custom objects so there's no field to edit. Idk if I need to set a dependency to change the order or if it's always like that.
<img width="567" alt="my error" src="https://github.com/spacechase0/StardewValleyMods/assets/104393392/5ab0ed67-0a44-4737-896f-7f34759cecad">

**Comment by spacechase0** [comment]
Hmm, actually, JA data largely doesn't exist until the save is loaded, so that might be why...

This might not be the case in 1.6 since item ID management is no longer necessary?

**Comment by sfortier32** [comment]
Yeah… I’m starting to see why the 1.6 update is so necessary. I think I’ll just leave out this part of the mod until then or try patching a custom version of DGA to include my token. Thanks for all your help!

Edit: I added the tokens into JA (hasItem and an extra one to return a string input so that the patch doesn't apply until the save is loaded) and it finally works. I'm gonna have the forked version of JA and some example code on my GitHub if anyone is trying to do this, but it'll all probably be irrelevant after 1.6 anyways.
