### ISSUE TITLE
SpaceCore Bug

### ISSUE THREAD

**Issue by mrtozkn** [spacechase0/StardewValleyMods#397]
Hi,

I'm getting this error on SMAPI;

[SpaceCore] NPC.DrawBreathing: some transpiler targets were not found. Aborting edit.

**Comment by babyyz** [comment]
me too, how do I solve it?

**Comment by KrumpledPaper** [comment]
Same, I've been troubleshooting for the past two hours and still nothing ;-;

**Comment by Scott-mods** [comment]
Get 1.5.6 codebase, check what the transpiler is(was) actually doing
Get 1.6 codebase, rewrite a new transpiler applying the same change to DrawBreathing

Alternatively, diff 1.5 and 1.6 and adjust transpiler accordingly.

It's not hard. I don't care about the feature at all, but apparently you do so I'm sure one of you will manage.

**Comment by spacechase0** [comment]
This was fixed in last night's build - the transpiler local number needed changing.
