### ISSUE TITLE
[Bug]: Game temporarily pauses when right clicking certain crops

### ISSUE THREAD

**Issue by Vivid141** [spacechase0/StardewValleyMods#403]
### **Description:**
Honestly, a little unsure how to describe this one. When I right click on certain crops in the ground that aren't mature (I've noticed the error happening with modded crops and wild spring forage seeds), the game freezes for as long as I hold down the right click on my mouse. It also returns a specific error in the log in red text. It's nothing game-breaking for me, but I thought it might be worth mentioning anyway since it's unusual behaviour.
_Edit:_ I've just noticed this also makes it impossible for me to harvest spring onions.

### **Versions:**
- Stardew Valley - 1.6.2
- SMAPI - 4.0.1
- Spacecore - 1.19.0

### **Log:** 
- Latest.log: https://smapi.io/log/c955b15d62294bcd869e59f495b19788

**Comment by Scott-mods** [comment]
Error looks genuine, but I'm not able to reproduce with any (summer) crops at any stage of maturity using the latest Core/SMapi and no other mod

**Comment by spacechase0** [comment]
This was already fixed.
