### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by mateus3c** [spacechase0/StardewValleyMods#440]
the dev of More Lively Sewer Overhaul said its probably caused and only fixeable by the spacecore side

![image](https://github.com/spacechase0/StardewValleyMods/assets/122059128/54a64625-eeef-4995-a61a-42e7d37dbfcc)

SMAPI gave me 2 logs:
normal log: https://smapi.io/log/15161d301b2642b68f98c9913f5c5a74
crash log: https://smapi.io/log/253435be3f4941bab2e3744e7d6d1ac8

**Comment by spacechase0** [comment]
Looks like an issue with Dynamic Reflections?

**Comment by mateus3c** [comment]
really? well, guess ill report to the Dynamic Reflections dev then. thank you!
