### ISSUE TITLE
DGA: Hitting Big Craftable with axe

### ISSUE THREAD

**Issue by echangda** [spacechase0/StardewValleyMods#47]
When I try to hit a Big Craftable with an axe to pick it up, it doesn't work and instead throws an error. It doesn't matter whether the axe is in position 1 or 2 of the toolbar, and it happens both indoors and outdoors. I only tested with one DGA big craftable, but there was nothing special about the big craftable (afaik, see json snippet below). It does not happen with vanilla big craftables.

Here are two logs where the error occurred. (It's very reproducible.)
https://smapi.io/log/0ecd715bee8a4ccb93f439b45efc21f5
https://smapi.io/log/0a78936e2acb4baf8b537d6efe1621d0

Here's the snippet where the Big Craftable was created:
{
        "$ItemType": "BigCraftable",
        "ID": "PurpleFloor3",
        "Texture": "floortall.png:0",
        "SellPrice": 1,
        "ProvidesLight": true,
}

**Comment by Pathoschild** [comment]
Fixed via #52 for the upcoming Dynamic Game Assets 1.2.1.
