### ISSUE TITLE
GMCM Keybind menu not opening with latest version: 1.13.0

### ISSUE THREAD

**Issue by jayrthrush2** [spacechase0/StardewValleyMods#478]
When opening the Keybinds menu, it does not open and an error is thrown in the SMAPI window.

[Here is my SMAPI log](https://smapi.io/log/b43aa0c84c8743aea0ba112ba0812147)

I'll have to go back to 1.12.0 until this is fixed

**Comment by spacechase0** [comment]
Attempted a fix in 1.13.1.
