### ISSUE TITLE
DGA : Improving error about missing file ?

### ISSUE THREAD

**Issue by Lumisteria** [spacechase0/StardewValleyMods#76]
https://smapi.io/log/a607f31ffd5548ee928edf4b7ad5dfa8

I got this error when trying to add an iconoverride for a context tag field

`
      {
        "Type": "ContextTag",
        "Value": "ingredient_salmon",
        "NameOverride": "Salmon or similar fish",
        "IconOverride": "override.png:0"
      },`

This was the relevant bit of code. The error was that there was no file "override.png". There was, however, an "objects/override.png"
Fixing the path solved the issue, but the error was confusing and something along the line of "no "override.png" file found" would have be more clearer, so in case this may be of any help for others, i'm suggesting this here.

**Comment by elizabethcd** [comment]
This has been fixed in the latest update (1.4.2).
