### ISSUE TITLE
[DGA] Can't craft more than 1 fence at a time.

### ISSUE THREAD

**Issue by sergiomadd** [spacechase0/StardewValleyMods#81]
The crafting recipe for DGA custom fences doesn't produce the specified amount of fences. 

In this example it just produces a single fence, even tho "Quantity": 5 is specified.
[Json code](https://pastebin.com/VKDXxtge)

**Comment by elizabethcd** [comment]
This actually appears to be true of any recipe that produces DGA objects, not just fences.
