### ISSUE TITLE
public access tv incompatibility

### ISSUE THREAD

**Issue by 123mind123** [spacechase0/StardewValleyMods#82]
The TV part of this mod is incompatible with and breaks the "public access tv" mod

**Comment by 123mind123** [comment]
This could maybe be fixed with the ability to turn of the TV part to the mod through the config.

**Comment by Pathoschild** [comment]
Magic adds its custom channel through PyTK, which hasn't been updated in a while. The upcoming Magic 0.8.0 removes the TV channel and adds a radio in the Wizard tower instead, so that won't be an issue anymore. Thanks for reporting it!
