### ISSUE TITLE
[DGA] Cooking recipes not showing as "learned".

### ISSUE THREAD

**Issue by BioKraze** [spacechase0/StardewValleyMods#84]
When creating crafting recipes in a DGA content pack with the field "IsCooking" set to "true", the recipes do not display as properly learned and thus craftable from the kitchen.

Log file generated, parsed and can be found here: [https://smapi.io/log/68649caeb8ee450ca258b7993e3bbbe7](url)

**Comment by elizabethcd** [comment]
I could not reproduce this issue. Do you have a content pack to reproduce it with?

**Comment by elizabethcd** [comment]
After further investigation, it looks like this is most likely caused by not declaring the Item Type as DGARecipe in the ShopEntry.

**Comment by BioKraze** [comment]
Do you know, you're very correct. Noob move for me, I suppose. Thank you for pinpointing the cause, and apologies for not checking this so for the very late reply!
