### ISSUE TITLE
[Capstone Profession] Change level == 10 by level >= 10

### ISSUE THREAD

**Issue by Schneitizel** [spacechase0/StardewValleyMods#87]
Hi

I use the Level Extender mod which allows me to go beyond level 10 in each skill
Except that once a skill reaches level 11 without me choosing a Capstone Profession bonus before, well I'm stuck, impossible to access the bonus for the rest of the game

https://github.com/spacechase0/StardewValleyMods/blob/1fc4d488e860a259987277bf7060f6d7fc2ffb9d/CapstoneProfessions/Mod.cs#L56

Here, it would be enough to replace the == 10 by >= 10 so that the mod remains compatible with the original levels AND the modded levels

Would it be possible to correct this, please?

Thanks !

**Comment by Pathoschild** [comment]
Fixed in the upcoming Capstone Professions 1.0.10. Thanks for reporting it!
