### ISSUE TITLE
GMCM: complex options have no way to respond to "Cancel"

### ISSUE THREAD

**Issue by jltaylor-us** [spacechase0/StardewValleyMods#89]
### Problem Statement
Despite the recent addition of several callbacks for supporting complex options, I still can't quite manage to make one that works as well as the built-in option types.  The last piece of functionality missing is a way to respond to the Cancel button.  Or, more accurately, a way to make complex options behave the same way as the built-in options when edits are made but cancelled, and then the menu is re-opened.

In the built-in option types, this works because `SpecificModConfigMenu` [calls](https://github.com/spacechase0/StardewValleyMods/blob/97e6fa15383972a2a50b9ddec55c8036603757ee/GenericModConfigMenu/Framework/SpecificModConfigMenu.cs#L84) `GetLatest` in its constructor.  Unfortunately, `GetLatest` in `ComplexModOption` [does nothing](https://github.com/spacechase0/StardewValleyMods/blob/main/GenericModConfigMenu/Framework/ModOption/ComplexModOption.cs#L88).

Here are three options for changes to the `AddComplexOption` API to support the "Cancel" behavior.  I can make a PR with any of these... I _think_ I prefer option 3, but 2 is also just fine.

### Option 1: Add an `onCancel` callback.  (Not recommended)

Since the problem is described as "cancel doesn't work", it seems logical to add a callback so that the complex option knows when the Cancel button was pressed.  However, this is not how the built-in options work, and not the behavior that's actually desired.  An arbitrary amount of time can pass between the Cancel button being pressed and the menu being reopened.  During that time, changes could be made to the configuration (e.g., via console commands), and we'd like the options to reflect the latest values when the menu is opened.

There is no reason not to add an `onCancel` callback for informational purposes, but it should not be the thing responsible for causing the complex option to refresh its value.

### Option 2: Add an `onMenuOpen` callback.

This is a straightforward substitution of the `GetLatest` call in `SpecificModConfigMenu` with a new `OnMenuOpen` function defined abstract in `BaseModOption`.  All of the remaining references to `GetLatest` are inside `SimpleModOption`, so it could be removed from `BaseModOption`.

**cons**: In order to make a complex option behave the same way as the built-in options, both `onMenuOpen` and `afterReset` will have to be specified - almost certainly as the same function.  (One extra line at the `AddComplexOption` call site is hardly a big issue.)

### Option 3: Add a `refreshValue` (or similar name) callback.

This replaces the empty `GetLatest` in `ComplexModOption` with an invocation of the callback.  Additionally, the `AfterReset` function could also call the `refreshValue` callback if the `AddComplexOption` call site does not supply an `afterReset` to override that behavior (i.e., if the `afterReset` callback is `null`).

**cons**: It is not obvious from the callback name exactly when `refreshValue` will be called.  The mod author just has to trust that GMCM will call it at the right time(s) and not try to intuit any other information about the menu lifecycle.

**Comment by Pathoschild** [comment]
Replacing `GetLatest` with `BeforeMenuOpened` + `BeforeMenuClosed` (essentially a beefed-up option 2) seems like the most flexible option. With that change, a complex option would have access to the entire menu lifecycle:

* before menu opened;
* update/render (_required_);
* before/after save;
* before/after reset;
* before menu closed.

**Comment by jltaylor-us** [comment]
Ok; how's #92 look?  It's a little more code than I was expecting, but I think I got everything.

**Comment by Pathoschild** [comment]
Thanks for the PR! Merged into `develop` via #92 for the upcoming Generic Mod Config Menu 1.8.0.
