### ISSUE TITLE
Add Ukrainian translations for Generic Mod Config Menu

### ISSUE THREAD

**Issue by ChulkyBow** [spacechase0/StardewValleyMods#90]
Could Ukrainian translation be added to GenericModConfigMenu mod?

P.S : Yes, there is already a Ukrainian Mod for Stardew Valley 1.5.5+, which adds a new custom language to the game (obviously it's Ukrainian). Ukrainian mod for SDV :  https://www.nexusmods.com/stardewvalley/mods/8427
[GenericModConfigMenu - Ukrainian.zip](https://github.com/spacechase0/StardewValleyMods/files/7801166/GenericModConfigMenu.-.Ukrainian.zip)

**Comment by Pathoschild** [comment]
Added in the upcoming Generic Mod Config Menu 1.7.1. Thanks for the help!
